# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2525ab4e1ec868044005c6ecba6ef9d2515324ebc663117a1dc97056438805c0bb639c2680e6dd1d1451129645048f26dbbfd371177363f3a89ad9ba957fd7c

test:
  secret_key_base: d8282973a6f66a374e244c49fdb056243827d62222520496c7a757805fb4d132e43e642279f89715bc4f062c0b9a3bf30c6a15672b5ddba31599579a65122179

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
